---
- name: Upload publish specific packages
  aempkg:
     name='{{item.name}}'
     state=uploaded
     admin_user='{{admin_user}}'
     admin_password='{{admin_password}}'
     host='{{inventory_hostname}}'
     port='{{port}}'
     path='{{packages_repo}}/{{item.file | default()}}'
  with_items: packages_publish
  tags: aem_packages_publish

- name: Install publish specific packages
  aempkg:
     name='{{item.name}}'
     state=present
     admin_user='{{admin_user}}'
     admin_password='{{admin_password}}'
     host='{{inventory_hostname}}'
     port='{{port}}'
     path='{{packages_repo}}/{{item.file | default()}}'
     wait=30
  with_items: packages_publish
  register: aem_packages_instance_installed
  tags: aem_packages_publish
