---
- name: Upload common packages
  aempkg:
     name='{{item.name}}'
     state=uploaded
     admin_user='{{admin_user}}'
     admin_password='{{admin_password}}'
     host='{{inventory_hostname}}'
     port='{{port}}'
     path='{{packages_repo}}/{{item.file | default()}}'
  with_items: packages_common
  tags: aem_packages_common

- name: Install common packages
  aempkg:
     name='{{item.name}}'
     state=present
     admin_user='{{admin_user}}'
     admin_password='{{admin_password}}'
     host='{{inventory_hostname}}'
     port='{{port}}'
     path='{{packages_repo}}/{{item.file | default()}}'
     wait=30
  with_items: packages_common
  register: aem_packages_common_installed
  tags: aem_packages_common
